BDTT-30
pandaponn/worldgate-track-trace pull request #15
Opened 2023-01-12 11:28 UTC by prussianman

# Description

Fixes [BDTT-30](https://bottlenose.atlassian.net/browse/BDTT-30)
- [x] New feature (non-breaking change which adds functionality)

List all acceptance criterias of user story and indicate which has been solved previously and which is solved currently

 - [x] Retrieve shipping info via BL number
 - [x] Retrieve shipping info from via Container number
 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have added the appropriate labels to my PR
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature work
- [x] New and existing unit tests pass locally with my changes

2023-01-12 16:08 UTC, pandaponn requested changes
Return JSON responses instead of printing to console and find elements by ID instead of XPATH.

2023-01-12 16:08 UTC, pandaponn commented on webscrapers/creds/goodrich.py
> +username = ""
Is it necessary to merge this file into main?

2023-01-12 22:39 UTC, prussianman commented on webscrapers/goodrich.py
> +        driver.switch_to.frame(driver.find_element(by=By.XPATH, value="/html/body/div[1]/iframe"))
When selecting by XPATH,

if there is an id, it seems like the XPATH generated will reference the element via id
```
            driver.find_element(by=By.XPATH, value="//*[@id=\"BlNo\"]").send_keys(tracking_identifier)
```

In cases where there isn't an id, either mix references will be used (id and then tags)
```
            driver.find_element(by=By.XPATH, value=" //*[@id=\"TAB1\"]/div[1]/div/div[3]/input").click()
 ```   
 or (just via tags :( )
``` 
           driver.switch_to.frame(driver.find_element(by=By.XPATH, value="/html/body/div[1]/iframe"))
```  
So I think it is fine to use XPATH? what do you think? For this particular iframe, there isn't an id

2023-01-12 22:45 UTC, prussianman commented on webscrapers/goodrich.py
> +from webdriver_manager.chrome import ChromeDriverManager
I think there isn't any difference, apart from not needing to specify chromedriver path in the code

2023-01-12 22:46 UTC, prussianman commented on webscrapers/creds/goodrich.py
> +username = ""
nope, there isnt

2023-01-12 23:06 UTC, prussianman commented on webscrapers/goodrich.py
> +        driver.switch_to.frame(driver.find_element(by=By.XPATH, value="/html/body/div[1]/iframe"))
Oh, I just searched, By.ID is faster, I'll make these changes

2023-01-13 06:58 UTC, pandaponn approved these changes
Great work here @prussianman, thanks for making the changes so quick.

2023-01-13 07:02 UTC, merged