[BDTT-11, BDTT-18] BE APIs for Sign Up and Sign In
pandaponn/worldgate-track-trace pull request #16
Opened 2023-01-12 11:33 UTC by charmjj

# Description

Fixes BDTT-11, BDTT-18

- DB: 
1. Modified wguser_id column datatype to varchar2(200),
2. Modified password column to password_hash 
3. Added new password_salt column

- BE APIs for Sign Up and Sign In

- README.md and Requirements.txt files

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have added the appropriate labels to my PR
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-01-12 15:38 UTC, JeffS97 requested changes

2023-01-12 15:38 UTC, JeffS97 commented on backend/app/user.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = "oracle://wg:wgdemo*()@202.73.56.175:1521/efprod" # TODO: Externalise into env config file
I dont think should include the username + password in this file, github will flag out as well and spam our emails. Can try adding into env?

2023-01-12 15:45 UTC, JeffS97 commented on backend/app/user.py
> +    password_hash = hashlib.sha512(
Not sure if database can store sha512 hash with varchar(200), need to test and check

2023-01-12 16:17 UTC, charmjj commented on backend/app/user.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = "oracle://wg:wgdemo*()@202.73.56.175:1521/efprod" # TODO: Externalise into env config file
done, also updated the README, gitignore and requirements.txt

2023-01-13 02:16 UTC, charmjj commented on backend/app/user.py
> +    password_hash = hashlib.sha512(
should be ok, 128 digits hexadecimal string < 200. I tested the api and no issues found

2023-01-13 03:47 UTC, JeffS97 approved these changes
Looks good to me

2023-01-13 03:48 UTC, merged